#!/bin/bash

convertsecs() {
	((d=${1}/86400))
	((h=(${1}%86400)/3600))
	((m=(${1}%3600)/60))
	((s=${1}%60))
	if (( $d > 0 )); then
		printf "%d jours, %d heures, %02d minutes et %02d secondes" $d $h $m $s
	elif (( $h > 0 )); then
		printf "%d heures, %02d minutes et %02d secondes" $h $m $s
	else
		printf "%02d minutes et %02d secondes" $m $s
	fi
}


RESHAPE=$(cat /proc/mdstat | grep reshape)

if [[ $RESHAPE ]]; then
	LAST_LINE=$RESHAPE
	FIRST_LINE=$(cat /proc/mdstat | grep -B 2 reshape | head -1)
	RESHAPE_MINS=$(echo $LAST_LINE | cut -d"]" -f 2 | cut -d"=" -f3 | cut -d "m" -f 1)
	RESHAPE_SECS_DOUBLE=$(echo "$RESHAPE_MINS*60" | bc)
	RESHAPE_SECS_INT=$(echo $RESHAPE_SECS_DOUBLE | cut -d"." -f 1)
	RESHAPE_DEVICE=$(echo $FIRST_LINE | cut -d' ' -f 1)
	PROGRESS=$(echo $LAST_LINE | cut -d"]" -f 2 | cut -d"=" -f2 | cut -d ' ' -f 2)
	echo "Reshape en cours de " $RESHAPE_DEVICE " (" $PROGRESS "). Temps restant : " $(convertsecs $RESHAPE_SECS_INT) " ETA : " `date -d "+ $RESHAPE_SECS_INT seconds"`
fi